"""Compile the Weaver registry's label vocabulary into an artifact the agent
carries at decision time.

The registry already knows the answer to "what is this label called": every
attribute records its idiomatic id (`app.outcome`) plus the flat key the code
actually emits (`note: Flat key in current code: \\`status\\``). But that
knowledge only ever ran at build time — `weaver.py` reduces the whole registry
to one boolean-ish alignment report, and the registry itself is not in the agent
image. So at decision time the agent had no way to ask the schema what a label
is called, and fell back on the prior every Prometheus user has: `service`.

That failure is quiet in the worst way. `sum by (service) (...)` is valid PromQL
against a store with no `service` label: Prometheus does not error, it collapses
every service into one unlabelled series. A wrong label here does not look like
a wrong label, it looks like a total.

So: same shape as `compile.py` and `weaver.py` — read the repo-side registry,
emit a committed artifact next to the compiled contracts, and let the runtime
read only the artifact. Fail-open: no registry (or an unreadable one) yields an
empty vocabulary, and callers simply inject nothing.

    python -m app.signals.vocabulary       # regenerate label_vocabulary.yaml
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field

logger = logging.getLogger("aiops_agent.signals.vocabulary")

VOCABULARY_VERSION = "1.0.0"

# Attributes record the emitted name as prose: "Flat key in current code: `x`".
# Metric groups record theirs as "Current code metric: `y`". Both are the
# registry's own convention for "the idiomatic name is the target, this is what
# ships today"; parsing them is what turns that prose into something machine
# readable.
_FLAT_KEY_RE = re.compile(r"Flat key in current code:\s*`([a-z_][a-z0-9_.]*)`")
_PROM_NAME_RE = re.compile(r"Current code metric:\s*`([a-z_][a-z0-9_]*)`")

_GENERATED_HEADER = (
    "# GENERATED by `python -m app.signals.vocabulary` from the Weaver registry\n"
    "# in demo-services/weaver/registry — DO NOT EDIT. Change the registry, then\n"
    "# recompile. This is the schema layer reaching decision time: the agent image\n"
    "# has no registry, so it reads this artifact instead.\n"
)


class Label(BaseModel):
    key: str  # what the store actually carries, e.g. `status`
    declared_as: str  # the registry's idiomatic id, e.g. `app.outcome`
    values: list[str] = Field(default_factory=list)  # enum domain, when declared
    note: str = ""


class MetricVocabulary(BaseModel):
    prom_name: str
    declared_as: str
    instrument: str = ""
    labels: list[Label] = Field(default_factory=list)


class Vocabulary(BaseModel):
    version: str = VOCABULARY_VERSION
    # Present on every signal from every service: the resource attributes.
    identity_labels: list[Label] = Field(default_factory=list)
    metrics: list[MetricVocabulary] = Field(default_factory=list)


def registry_dir(path: Path | None = None) -> Path:
    """The repo-side registry. app/signals/vocabulary.py → parents[4] = repo root."""
    if path:
        return path
    from ..config import settings

    if settings.weaver_registry_path:
        # settings points at the metrics model file; the vocabulary needs the dir.
        p = Path(settings.weaver_registry_path)
        return p.parent if p.is_file() else p
    return Path(__file__).parents[4] / "demo-services/weaver/registry/model"


def _load(p: Path) -> dict[str, Any]:
    try:
        return yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    except Exception as e:
        logger.warning("registry model not readable (%s): %s", p, e)
        return {}


def _flat_key(attr: dict) -> str:
    """The name this attribute is emitted under today, or its id when the code
    already matches the registry. An attribute whose flat key we cannot resolve
    is skipped rather than guessed — a vocabulary that guesses is the problem it
    was written to solve."""
    m = _FLAT_KEY_RE.search(attr.get("note") or "")
    if m:
        return m.group(1)
    aid = attr.get("id") or ""
    return aid if aid and "." not in aid else ""


def _values(attr: dict) -> list[str]:
    t = attr.get("type")
    if not isinstance(t, dict):
        return []
    return [str(m["value"]) for m in t.get("members", []) if m.get("value") is not None]


def _attribute_index(model_dir: Path) -> dict[str, Label]:
    """Every attribute the registry defines, keyed by its idiomatic id, so a
    metric's `ref:` can be resolved to the flat key the store carries."""
    index: dict[str, Label] = {}
    for f in sorted(model_dir.glob("*.yaml")):
        for g in _load(f).get("groups", []) or []:
            for a in g.get("attributes", []) or []:
                aid = a.get("id")
                if not aid:
                    continue  # a `ref:` entry, not a definition
                key = _flat_key(a)
                if not key:
                    continue
                index[aid] = Label(
                    key=key,
                    declared_as=aid,
                    values=_values(a),
                    note=" ".join((a.get("note") or "").split()),
                )
    return index


def _resource_labels(model_dir: Path, index: dict[str, Label]) -> list[Label]:
    """The labels every signal carries, taken from the registry's `resource`
    groups rather than hardcoded here — the point of this module is that the
    registry is the source of truth for names."""
    out: dict[str, Label] = {}
    for f in sorted(model_dir.glob("*.yaml")):
        for g in _load(f).get("groups", []) or []:
            if g.get("type") != "resource":
                continue
            for a in g.get("attributes", []) or []:
                ref = a.get("ref") or a.get("id")
                if ref and ref in index:
                    out[ref] = index[ref]
    return sorted(out.values(), key=lambda label: label.key)


def build_vocabulary(model_dir: Path | None = None) -> Vocabulary:
    d = model_dir or registry_dir()
    if not d.is_dir():
        logger.warning("registry model dir not found: %s", d)
        return Vocabulary()
    index = _attribute_index(d)
    metrics: list[MetricVocabulary] = []
    for g in _load(d / "metrics.yaml").get("groups", []) or []:
        if g.get("type") != "metric":
            continue
        m = _PROM_NAME_RE.search(g.get("note") or "")
        if not m:
            continue  # declared but not yet emitted; nothing to query by
        labels = [
            index[ref] for a in g.get("attributes", []) or [] if (ref := a.get("ref")) in index
        ]
        metrics.append(
            MetricVocabulary(
                prom_name=m.group(1),
                declared_as=g.get("metric_name") or g.get("id") or "",
                instrument=g.get("instrument") or "",
                labels=labels,
            )
        )
    return Vocabulary(
        identity_labels=_resource_labels(d, index),
        metrics=sorted(metrics, key=lambda x: x.prom_name),
    )


def vocabulary_path() -> Path:
    return Path(__file__).parent / "label_vocabulary.yaml"


def get_vocabulary(path: Path | None = None) -> Vocabulary:
    """The compiled artifact, or an empty vocabulary when it is absent."""
    p = path or vocabulary_path()
    try:
        return Vocabulary.model_validate(yaml.safe_load(p.read_text(encoding="utf-8")))
    except Exception as e:
        logger.warning("label vocabulary not readable (%s): %s", p, e)
        return Vocabulary()


def render_vocabulary(vocab: Vocabulary | None = None) -> str:
    """The block injected into a turn. Keys only, no value domains.

    Deliberate omission: the registry's enum members include this demo's
    incident reasons, and injecting them would hand the agent the answer it is
    supposed to discover — the exact leak the eval harness scans for. Label
    *names* are the environment's shape (fair to hand over); label *values* are
    frequently the finding.
    """
    v = vocab or get_vocabulary()
    if not v.metrics and not v.identity_labels:
        return ""
    lines = [
        "## Label vocabulary (compiled from the Weaver registry)",
        "",
        "Authoritative label names for this environment. Use these verbatim; do "
        "not substitute conventional names. A label that does not exist does not "
        "error in PromQL — `sum by (<wrong>)` silently returns one unlabelled "
        "total, which reads like a working query.",
        "",
        "On every metric, log line and span:",
    ]
    for label in v.identity_labels:
        lines.append(f"- `{label.key}` (declared as `{label.declared_as}`)")
    if v.metrics:
        lines += ["", "Per-metric labels (in addition to the above):"]
        for m in v.metrics:
            keys = ", ".join(f"`{label.key}`" for label in m.labels) or "—"
            lines.append(f"- `{m.prom_name}` ({m.instrument}): {keys}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":  # pragma: no cover
    vocab = build_vocabulary()
    if not vocab.metrics:
        print(f"⚠ no metrics resolved from {registry_dir()}; wrote nothing")
        raise SystemExit(1)
    body = yaml.safe_dump(vocab.model_dump(), sort_keys=False, allow_unicode=True, width=100)
    vocabulary_path().write_text(_GENERATED_HEADER + body, encoding="utf-8")
    print(
        f"compiled {len(vocab.metrics)} metric(s) + "
        f"{len(vocab.identity_labels)} identity label(s) → {vocabulary_path().name}"
    )
    for label in vocab.identity_labels:
        print(f"  identity: {label.key:<24} ({label.declared_as})")
